name: PR Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint-frontend:
    name: Lint Vue.js Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./algotrace.client 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: ./algotrace.client/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

    - name: Build and Type Check
      run: npm run build

  lint-backend:
    name: Lint ASP.NET Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore AlgoTrace.slnx 

    - name: Check formatting and linting
      run: dotnet format AlgoTrace.slnx --verify-no-changes

    - name: Build project
      run: dotnet build AlgoTrace.slnx --no-restore